language: go
go_import_path: github.com/clearcontainers/proxy
go:
        - 1.7
        - tip

env:
        - secure: "i42CSCRUODiB1HaeDRo/7hU5agrxq0WpDR9O8kYCjwEqUKyOCui32u5MxzFI/A7Uq/V2F2dOukTicT60KbvEwKwVz/idqkyhpm9xgxxZNCi1hWDPYaf4nVBGKT7o9tkGDJGBJzhQOsVxPbxq2EAEbzG0pISO+MV6LDol7wnm5fT+yStZJHvjyV4ZZqCfvSkKjHNifsHdK7vQCgUCmAsTjKNpcnigBcQ52Epnijv0gm447XNB6g/4ceK6FiuzLetWbshQwxjyfC0PxL34UKqyruHA/3sWVDLtvTqUiJPsmMFAkSdT8COdbRC7Io4445PKj3vrTg/ugVIJFQsUxt+0uWgvGYSupNHOI3/2sPQ0a60E9kGZqBtGSq6a0hLZ+Rm3iyIpvG1JC9zH1SDvd5qvsW7DoeA3psBdTfwiqanR42gvUgMg/PzpA1Xox4s768cMYmQgq5oRtmcvMqh/59SX/Vmg/gFSqkzvtC3QQpdQNyDv2lQQg5aUatySs6SbXVrkqdep6DQu5Xg8AWrAnHOiw3/njQ4C9R0YOQciZ082xVe1kb66KQZpKzJBGyeOr9HkaRdxEvRtclylkXXub5f0KUxebFs3MKOUO14/mCe9OXFMoANuFpWTSdr0bKfYkpqhAme/PZ0QDQUWDmr2Kezt1epOs0URF/xjQ6A5kKtsYbM="

script:
        - make
        - make check

after_success:
        - go get github.com/mattn/goveralls
        - $GOPATH/bin/goveralls -service=travis-ci -coverprofile=profile.cov
